const employees = [
  {
    id: "E001",
    firstname: "Rahul",
    lastname: "Sharma",
    email: "e@e.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskNumber: 1,
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
        taskTitle: "Task 1",
        taskDescription: "Complete the project proposal.",
        taskDate: "2025-03-30",
        category: "Work",
      },
      {
        taskNumber: 2,
        active: true,
        newTask: false,
        completedTask: true,
        failedTask: false,
        taskTitle: "Task 2",
        taskDescription: "Update the project document.",
        taskDate: "2025-03-25",
        category: "Work",
      },
      {
        taskNumber: 3,
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
        taskTitle: "Task 3",
        taskDescription: "Fix bugs in the system.",
        taskDate: "2025-03-20",
        category: "Maintenance",
      },
    ],
  },
  {
    id: "E002",
    firstname: "Priya",
    lastname: "Desai",
    email: "employee2@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskNumber: 1,
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
        taskTitle: "Task 1",
        taskDescription: "Prepare the design mockups.",
        taskDate: "2025-03-30",
        category: "Design",
      },
      {
        taskNumber: 2,
        active: true,
        newTask: false,
        completedTask: false,
        failedTask: false,
        taskTitle: "Task 2",
        taskDescription: "Collaborate with the marketing team.",
        taskDate: "2025-03-28",
        category: "Collaboration",
      },
      {
        taskNumber: 3,
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        taskTitle: "Task 3",
        taskDescription: "Submit the project proposal.",
        taskDate: "2025-03-22",
        category: "Work",
      },
    ],
  },
  {
    id: "E003",
    firstname: "Vikram",
    lastname: "Reddy",
    email: "employee3@example.com",
    password: "123",
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskNumber: 1,
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
        taskTitle: "Task 1",
        taskDescription: "Write the user guide.",
        taskDate: "2025-03-30",
        category: "Documentation",
      },
      {
        taskNumber: 2,
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        taskTitle: "Task 2",
        taskDescription: "Test the new features.",
        taskDate: "2025-03-25",
        category: "Testing",
      },
    ],
  },
  {
    id: "E004",
    firstname: "Ananya",
    lastname: "Gupta",
    email: "employee4@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        taskNumber: 1,
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
        taskTitle: "Task 1",
        taskDescription: "Attend the sprint planning meeting.",
        taskDate: "2025-03-30",
        category: "Meeting",
      },
      {
        taskNumber: 2,
        active: true,
        newTask: false,
        completedTask: false,
        failedTask: true,
        taskTitle: "Task 2",
        taskDescription: "Fix security vulnerabilities.",
        taskDate: "2025-03-28",
        category: "Security",
      },
      {
        taskNumber: 3,
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        taskTitle: "Task 3",
        taskDescription: "Document the new feature.",
        taskDate: "2025-03-22",
        category: "Documentation",
      },
    ],
  },
  {
    id: "E005",
    firstname: "Amit",
    lastname: "Kumar",
    email: "employee5@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        taskNumber: 1,
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
        taskTitle: "Task 1",
        taskDescription: "Research new technologies for the project.",
        taskDate: "2025-03-30",
        category: "Research",
      },
      {
        taskNumber: 2,
        active: true,
        newTask: false,
        completedTask: true,
        failedTask: false,
        taskTitle: "Task 2",
        taskDescription: "Write the technical documentation.",
        taskDate: "2025-03-25",
        category: "Documentation",
      },
      {
        taskNumber: 3,
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
        taskTitle: "Task 3",
        taskDescription: "Complete unit tests for the new module.",
        taskDate: "2025-03-20",
        category: "Testing",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    firstname: "Sandeep",
    email: "admin@example.com",
    password: "123",
  },
];

// Function to update localStorage with tasks and task numbers
export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin")); // Corrected: it should fetch "admin" from localStorage

  return { employees, admin };
};
